spring:
#  main:
#    allow-bean-definition-overriding: true
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8090

#user:
#  oauth:
#    clientId: javadevjournal
#    clientSecret: 1234$#@!
#    redirectUris: http://localhost:8090/login
#    username: javadevjournal
#    password: javadevjournal
#    accessTokenValidity: 300
#    refreshTokenValidity: 240000

